# Generated by Django 4.1.4 on 2022-12-19 11:38

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('tipo', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], default='D', max_length=1, verbose_name='Tipo')),
                ('nomConta', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Razao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('periodoInicial', models.DateField(verbose_name='Período Inicial')),
                ('periodoFinal', models.DateField(verbose_name='Período Final')),
                ('saldoAnterior', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Saldo Anterior')),
                ('entradas', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Entradas')),
                ('saidas', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Saídas')),
                ('saldoFinal', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Saldo Final')),
                ('situacao', models.BooleanField(default=True, verbose_name='Situação?')),
                ('nomeConta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contabilidade.conta', verbose_name='Conta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('dataNota', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('imprimir', models.BooleanField(default=True, verbose_name='Imprimir?')),
                ('contaCredito', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Credito', to='contabilidade.conta', verbose_name='Conta')),
                ('contaDebito', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Debito', to='contabilidade.conta', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='equipe', variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Foto')),
                ('cargo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contabilidade.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
    ]
