# Generated by Django 4.1.4 on 2022-12-21 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='razao',
            options={'verbose_name': 'Razao', 'verbose_name_plural': 'Razoes'},
        ),
        migrations.AlterField(
            model_name='nota',
            name='contaCredito',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Credito', to='contabilidade.conta', verbose_name='Conta Crédito'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='contaDebito',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Debito', to='contabilidade.conta', verbose_name='Conta Débito'),
        ),
    ]
