# Generated by Django 4.1.4 on 2023-01-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0003_alter_equipe_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='descricao',
            field=models.TextField(default='Vlr. ref. ', max_length=200, verbose_name='Descrição'),
        ),
    ]
