# Generated by Django 6.0.5 on 2026-06-09 01:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacredora',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo no momento do cadastro da conta. Não altere manualmente.', max_digits=9),
        ),
        migrations.AddField(
            model_name='contadevedora',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo no momento do cadastro da conta. Não altere manualmente.', max_digits=9),
        ),
        migrations.AlterField(
            model_name='contacredora',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculado automaticamente a partir das partidas.', max_digits=9),
        ),
        migrations.AlterField(
            model_name='contadevedora',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculado automaticamente a partir das partidas.', max_digits=9),
        ),
    ]
